const wordList = [
    { word: 'array', hint: 'A data structure for storing multiple values.' },
    { word: 'event', hint: 'An action like click, keypress, or load.' },
    { word: 'fetch', hint: 'Used to make HTTP requests.' },
    { word: 'scope', hint: 'Determines the visibility of variables.' },
    { word: 'JSON', hint: 'Data format often used in APIs.' },
    { word: 'async', hint: 'Keyword for writing asynchronous code.' },
    { word: 'await', hint: 'Pauses async code until a promise resolves.' },
    { word: 'regex', hint: 'Used to match patterns in strings.' },
    { word: 'stack', hint: 'LIFO data structure for managing data.' },
    { word: 'NaN',   hint: 'Represents "Not a Number".' },
    { word: 'null', hint: 'Represents an intentional absence of value.' },
    { word: 'const', hint: 'Defines a block-scoped constant variable.' },
    { word: 'props', hint: 'Properties passed to components in React.' },
    { word: 'array', hint: 'Used to store a list of items.' },
    { word: 'click', hint: 'Mouse event triggered by pressing a button.' },
    { word: 'class', hint: 'Template for creating objects.' },
    { word: 'slice', hint: 'Returns a portion of an array.' },
    { word: 'index', hint: 'Position of an element in an array.' },
    { word: 'while', hint: 'A loop that runs as long as the condition is true.' },
    { word: 'false', hint: 'A boolean value indicating "no" or "not true".' },
    { word: 'debug', hint: 'Finding and fixing code issues.' },
    { word: 'light', hint: 'Opposite of dark mode.' },
    { word: 'mouse', hint: 'Hardware for pointing and clicking.' },
    { word: 'login', hint: 'Authentication process to access accounts.' },
    { word: 'input', hint: 'Element to accept user data in forms.' },
    { word: 'table', hint: 'HTML element to display data in rows and columns.' },
    { word: 'modal', hint: 'A popup dialog box on a webpage.' },
    { word: 'image', hint: 'A visual media file on the web.' },
    { word: 'local', hint: 'Scope limited to the current context.' },
    { word: 'slice', hint: 'Extracts a portion of a string or array.' },
    { word: 'focus', hint: 'Active state for an input field.' },
    { word: 'timer', hint: 'Tracks time intervals in code.' },
    { word: 'alert', hint: 'Displays a message to the user.' },
    { word: 'value', hint: 'The content held by a variable.' },
    { word: 'equal', hint: 'Used to compare two values.' },
    { word: 'query', hint: 'Request for information in a database.' },
    { word: 'reset', hint: 'Clears input fields or states.' },
    { word: 'hover', hint: 'Mouse action over an element without clicking.' },
    { word: 'modal', hint: 'A temporary window for user interaction.' },
    { word: 'split', hint: 'Divides a string into an array.' },
    { word: 'merge', hint: 'Combines multiple elements into one.' },
    { word: 'event', hint: 'Action like a click or hover.' },
    { word: 'input', hint: 'Field for user data entry.' },
    { word: 'valid', hint: 'Indicates that data is correct or acceptable.' },
    { word: 'error', hint: 'An issue or bug in the program.' },
    { word: 'cache', hint: 'Stores data for quick access.' },
    { word: 'float', hint: 'CSS property for aligning elements.' },
    { word: 'width', hint: 'Defines the size of an element horizontally.' },
    { word: 'array', hint: 'Collection of ordered data.' },
    { word: 'modal', hint: 'Temporary on-screen box for user input.' },
];
